.section .data
cactus:
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 1 # data 1
    .byte 1 # data 1
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 1 # data 1
    .byte 1 # data 1
    .byte 1 # data 1
    .byte 1 # data 1
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 1 # data 1
    .byte 1 # data 1
    .byte 1 # data 1
    .byte 1 # data 1
    .byte 0 # data 0
    .byte 0 # data 0
    .byte 1 # data 1
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 0
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 0
    .byte 1
    .byte 1
    .byte 1
    .byte 1
    .byte 0
    .byte 0
    .byte 0
    .byte 0
.section .text
.globl print_cactus # print_cactus
.type print_cactus, @function # print_cactus
print_cactus: # print_cactus
# draw cactus_5
    addi sp, sp, -4 # sp = sp - 4
    sw ra, 0(sp) # sp[0] = ra
    la t0 , cactus # t0 = cactus

    li t1, 0     # init i = 0
    li t2, 0     # inti j = 0
    li t3, 11    # imax
    li t4, 24    # jmax
    # mv s0, a0    # x
    # mv s1, a1    # y

    loop_i:
        bge t1, t3, exit_loop_i   # for (; i < 18; ++i)
        li t2, 0     # j = 0
        loop_j:
            bge t2, t4, exit_loop_j # for (int j = 0; j < 24; ++j)
                # get cactus[j][i]
                # which should be t0 + 11 * j + i
                mv t5, t1    # +i
                add t5, t5, t0    # +i+t0
                li t6, 11
                mul t6, t6, t2    # 11 * j
                add t5, t5, t6    # +i+t0+11j
                lb t6, 0(t5)     # t6 is cactus_5[j][i]
                beq t6, x0, black_point   #if (cactus_5[j][i] == 1)
                    # LCD_DrawPoint(x + i, y + j, WHITE);
                    add a0, s0, t1
                    add a1, s1, t2
                    li a3, 0xFFFF
                    # call LCD_DrawPoint
                    jal x0, end_if
                black_point:
                    # LCD_DrawPoint(x + i, y + j, BLACK);
                    add a0, s0, t1
                    add a1, s1, t2
                    li a3, 0x0000
                    # call LCD_DrawPoint
                end_if:
            addi t2, t2, 1    # ++j
            jal x0, loop_j
        exit_loop_j:
        addi t1, t1, 1    # ++i
        jal x0, loop_i
    exit_loop_i:

    lw ra, 0(sp) #load ra from stack
    addi sp, sp, 4 #addi sp,sp,4
    ret #ret


